-- iCensus Database Backup
-- Created: 2025-09-25 10:31:49

DROP TABLE IF EXISTS `analytics_layouts`;
CREATE TABLE `analytics_layouts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `layout` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`layout`)),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `barangay_settings`;
CREATE TABLE `barangay_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `barangay_name` varchar(100) NOT NULL,
  `municipality` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `logo_path` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `barangay_settings` (`id`, `barangay_name`, `municipality`, `province`, `logo_path`, `created_at`) VALUES ('1', 'My Barangay', 'My Municipality', 'My Province', NULL, '2025-08-14 11:40:40');

DROP TABLE IF EXISTS `chart_settings`;
CREATE TABLE `chart_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `metric` varchar(50) NOT NULL,
  `chart_type` enum('PieChart','DonutChart','BarChart','ColumnChart') NOT NULL DEFAULT 'PieChart',
  `width` int(11) DEFAULT 600,
  `height` int(11) DEFAULT 400,
  `colors` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `chart_settings` (`id`, `metric`, `chart_type`, `width`, `height`, `colors`) VALUES ('1', 'gender', 'PieChart', '600', '400', NULL);
INSERT INTO `chart_settings` (`id`, `metric`, `chart_type`, `width`, `height`, `colors`) VALUES ('2', 'civil_status', 'BarChart', '600', '400', NULL);
INSERT INTO `chart_settings` (`id`, `metric`, `chart_type`, `width`, `height`, `colors`) VALUES ('3', 'age_groups', 'ColumnChart', '600', '400', NULL);
INSERT INTO `chart_settings` (`id`, `metric`, `chart_type`, `width`, `height`, `colors`) VALUES ('4', 'blood_type', 'DonutChart', '600', '400', NULL);
INSERT INTO `chart_settings` (`id`, `metric`, `chart_type`, `width`, `height`, `colors`) VALUES ('5', 'residency_status', 'ColumnChart', '600', '400', NULL);
INSERT INTO `chart_settings` (`id`, `metric`, `chart_type`, `width`, `height`, `colors`) VALUES ('6', 'status', 'PieChart', '600', '400', NULL);

DROP TABLE IF EXISTS `residents`;
CREATE TABLE `residents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(50) NOT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) NOT NULL,
  `suffix` varchar(10) DEFAULT NULL,
  `nickname` varchar(50) DEFAULT NULL,
  `dob` date NOT NULL,
  `gender` varchar(10) NOT NULL,
  `civil_status` varchar(20) DEFAULT NULL,
  `blood_type` varchar(5) DEFAULT NULL,
  `nationality` varchar(50) DEFAULT NULL,
  `contact_number` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `emergency_name` varchar(100) DEFAULT NULL,
  `emergency_relation` varchar(50) DEFAULT NULL,
  `emergency_number` varchar(20) DEFAULT NULL,
  `house_no` varchar(20) DEFAULT NULL,
  `street` varchar(100) DEFAULT NULL,
  `purok` varchar(50) DEFAULT NULL,
  `barangay` varchar(100) DEFAULT NULL,
  `head_of_household` varchar(100) DEFAULT NULL,
  `head_of_household_id` int(11) DEFAULT NULL,
  `relationship` varchar(50) DEFAULT NULL,
  `residency_status` varchar(20) DEFAULT 'Resident',
  `status` varchar(20) DEFAULT 'Active',
  `date_added` datetime DEFAULT current_timestamp(),
  `last_updated` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `head_of_household_id` (`head_of_household_id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('3', 'Pedro', 'Reyes', 'Gomez', '', 'Pete', '1978-11-05', 'Male', 'Married', 'B-', 'Filipino', '09175678901', 'pedro@example.com', 'Lucia Reyes', 'Spouse', '09176543210', '18', 'Coconut Rd', '3', 'Barangay 3', 'Pedro Reyes', NULL, 'Self', 'Resident', 'Inactive', '2025-08-27 15:48:05', '2025-08-27 15:48:05');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('4', 'Ana', 'Lopez', 'Martinez', '', 'Ann', '2001-07-12', 'Female', 'Single', 'AB+', 'Filipino', '09171239876', 'ana@example.com', 'Jose Lopez', 'Father', '09171234567', '22', 'Pine St', '4', 'Barangay 1', 'Ana Lopez', NULL, 'Self', 'Resident', 'Active', '2025-08-27 15:48:05', '2025-08-27 15:48:05');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('5', 'Carlos', 'Dela', 'Ramos', '', 'Carl', '1995-12-30', 'Male', 'Single', 'O-', 'Filipino', '09174561234', 'carlos@example.com', 'Elena Ramos', 'Mother', '09175612345', '7', 'Guava St', '2', 'Barangay 2', 'Carlos Ramos', NULL, 'Self', 'Resident', 'Moved', '2025-08-27 15:48:05', '2025-08-27 15:48:05');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('6', 'Juan', '', 'Cruz', '', '', '1985-06-15', 'Male', '', '', '', '09171234567', 'juan@example.com', 'Maria Dela Cruz', 'Spouse', '09179876543', '12', 'Mango St', '1', 'Barangay 1', 'Juan Dela Cruz', NULL, 'Self', 'Resident', 'Moved', '2025-08-27 10:24:36', '2025-08-27 10:24:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('9', 'Jeremy Benson', 'Garcia', 'Lastrollo', '', '', '2003-02-26', 'Male', '', '', '', '09955554583', 'jeremybensonlastrollo@gmail.com', 'Josefina G. Lastrollo', 'Mother', '09164120545', '3001', 'Palmera', '3', 'Cofradia', 'Benjamin M. Lastrollo', NULL, 'father', 'Resident', 'Active', '2025-08-27 10:47:38', '2025-08-27 10:47:38');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('10', 'Jeremy Benson', 'Garcia', 'Lastrollo', '', '', '2003-02-26', 'Male', '', '', '', '09955554583', 'jeremybensonlastrollo@gmail.com', 'Josefina G. Lastrollo', 'Mother', '09164120545', '3001', 'Palmera', '3', 'Cofradia', 'Benjamin M. Lastrollo', NULL, 'father', 'Resident', 'Deceased', '2025-08-28 02:25:09', '2025-08-28 02:25:09');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('11', 'Juan woww pogi 34', '', 'Cruz', '', '', '1985-06-15', 'Male', '', '', '', '09171234567', 'juan@example.com', 'Maria Dela Cruz', 'Spouse', '09179876543', '12', 'Mango St', '1', 'Barangay 1', '', NULL, '', 'Resident', 'Active', '2025-08-28 03:47:40', '2025-09-25 06:40:51');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('12', 'Juan', 'Dela', 'Cruz', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 1', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('13', 'Maria', 'Santos', 'Reyes', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 2', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('14', 'Jose', 'Lopez', 'Garcia', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 3', NULL, NULL, NULL, 'Resident', 'Inactive', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('15', 'Ana', 'Perez', 'Ramos', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 4', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('16', 'Pedro', 'Castro', 'Mendoza', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 5', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('17', 'Lucia', 'Flores', 'Diaz', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 6', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('18', 'Ramon', 'Torres', 'Gonzales', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 7', NULL, NULL, NULL, 'Resident', 'Inactive', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('19', 'Elena', 'Cruz', 'Navarro', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 8', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('20', 'Manuel', 'Santos', 'Villanueva', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 9', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('21', 'Rosa', 'Reyes', 'Domingo', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 10', NULL, NULL, NULL, 'Resident', 'Inactive', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('22', 'Carlos', 'Garcia', 'Morales', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 11', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('23', 'Isabel', 'Ramos', 'Gutierrez', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 12', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('24', 'MiguelWow', 'Mendoza', 'Pascual', '', '', '2000-02-02', 'Male', '', '', '', '', '', '', '', '', '2', '2', '2', 'Barangay 13', '', NULL, '', 'Resident', 'Active', '2025-08-28 07:20:54', '2025-08-28 07:20:54');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('25', 'Sofia', 'Diaz', 'Velasco', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 14', NULL, NULL, NULL, 'Resident', 'Inactive', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('26', 'Andres', 'Gonzales', 'Aquino', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 15', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('27', 'Carmen wowerz', 'Navarro', 'montenegro', '', '', '2000-02-02', 'Female', '', '', '', '', '', '', '', '', '2', '22', '2', 'Barangay 16', '', NULL, '', 'Resident', 'Active', '2025-08-28 04:04:38', '2025-08-28 04:04:38');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('28', 'Diego', 'Villanueva', 'Salazar', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 17', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('29', 'Teresa', 'Domingo', 'Marquez', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 18', NULL, NULL, NULL, 'Resident', 'Inactive', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('30', 'Javier', 'Morales', 'Calderon', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 19', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('31', 'Beatriz', 'Gutierrez', 'Ortega', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 20', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('32', 'Francisco', 'Pascual', 'Delos Santos', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 21', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('33', 'Angela3', 'Velasco', 'Bautista', '', '', '2000-04-04', 'Female', '', '', '', '', '', '', '', '', '4', '4', '4', 'Barangay 22', '', NULL, '', 'Resident', 'Inactive', '2025-08-28 09:56:29', '2025-09-23 07:39:02');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('34', 'Ricardo', 'Aquino', 'Fernandez', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 23', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('35', 'Patricia', 'Aguilar', 'Dominguez', NULL, NULL, '0000-00-00', 'Female', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 24', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('36', 'Eduardo', 'Salazar', 'Hernandez', NULL, NULL, '0000-00-00', 'Male', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Barangay 25', NULL, NULL, NULL, 'Resident', 'Active', '2025-08-28 09:56:29', '2025-08-28 09:56:29');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('37', 'Carmen334', 'Navarro Wow', 'Aguilar', '', '', '2025-08-13', 'Female', '', '', '', '', '', '', '', '', '2', '2', '3', 'Barangay 16', '', NULL, '', 'Resident', 'Active', '2025-09-13 10:48:52', '2025-09-13 10:48:52');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('38', 'Juan', 'Wow', 'Cruz', '', '', '2003-02-02', 'Male', '', '', '', '09179876543', 'juan@example.com', '', '', '', '12', 'Mango St', '1', 'Barangay 1', '', NULL, '', 'Resident', 'Active', '2025-08-28 04:17:06', '2025-08-28 04:17:06');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('39', 'Juan', 'Landayan', 'Cruz', '', '', '2000-06-09', 'Male', '', '', '', '09179876543', 'juan@example.com', '', '', '', '12', 'Mango St', '1', 'Barangay 1', '', NULL, '', 'Resident', 'Active', '2025-08-28 05:04:04', '2025-08-28 05:04:04');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('40', 'Angelo', 'Landayan', 'Carpio', '', '', '2020-12-27', 'Male', '', '', '', '12312312312', 'admin@example.com', 'Maria Dela Cruz', 'Mother', '12312312312', '3', '3', '3', 'Balagtas', '', NULL, '', 'Resident', 'Active', '2025-08-28 09:12:56', '2025-08-28 09:12:56');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('41', 'John', 'A.', 'Doe', NULL, 'Johnny', '1990-05-14', 'Male', 'Single', 'O+', 'Filipino', '09171234567', 'john.doe@example.com', 'Jane Doe', 'Sister', '09179876543', '123', 'Maple Street', 'Purok 1', 'Barangay Uno', 'Michael Doe', '1', 'Son', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('42', 'Maria', 'B.', 'Santos', NULL, 'Mari', '1985-09-21', 'Female', 'Married', 'A+', 'Filipino', '09172345678', 'maria.santos@example.com', 'Jose Santos', 'Husband', '09171239876', '45', 'Cebu Street', 'Purok 2', 'Barangay Dos', 'Jose Santos', '2', 'Wife', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('43', 'Kevin', 'C.', 'Reyes', NULL, 'Kev', '2000-12-02', 'Male', 'Single', 'B+', 'Filipino', '09173456789', 'kevin.reyes@example.com', 'Ana Reyes', 'Mother', '09172345678', '78', 'Mango Avenue', 'Purok 3', 'Barangay Tres', 'Ana Reyes', '3', 'Son', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('44', 'Angela', NULL, 'Lopez', NULL, 'Angie', '1992-07-10', 'Female', 'Single', 'AB+', 'Filipino', '09174567890', 'angela.lopez@example.com', 'Roberto Lopez', 'Father', '09173456789', '32', 'Banana Street', 'Purok 1', 'Barangay Uno', 'Roberto Lopez', '4', 'Daughter', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('45', 'Mark', 'D.', 'Garcia', NULL, 'Marc', '1988-11-05', 'Male', 'Married', 'O-', 'Filipino', '09175678901', 'mark.garcia@example.com', 'Liza Garcia', 'Wife', '09174567890', '12', 'Pine Street', 'Purok 2', 'Barangay Dos', 'Liza Garcia', '5', 'Husband', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('46', 'Sophia', NULL, 'Torres', NULL, 'Sophie', '1995-03-18', 'Female', 'Single', 'A-', 'Filipino', '09176789012', 'sophia.torres@example.com', 'Maria Torres', 'Mother', '09175678901', '56', 'Cherry Lane', 'Purok 3', 'Barangay Tres', 'Maria Torres', '6', 'Daughter', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('47', 'Daniel', 'E.', 'Fernandez', NULL, 'Dan', '1993-06-22', 'Male', 'Single', 'B-', 'Filipino', '09177890123', 'daniel.fernandez@example.com', 'Carlos Fernandez', 'Father', '09176789012', '9', 'Guava Street', 'Purok 1', 'Barangay Uno', 'Carlos Fernandez', '7', 'Son', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('48', 'Lara', NULL, 'Martinez', NULL, 'Lari', '1997-08-30', 'Female', 'Single', 'O+', 'Filipino', '09178901234', 'lara.martinez@example.com', 'Sofia Martinez', 'Mother', '09177890123', '21', 'Peach Street', 'Purok 2', 'Barangay Dos', 'Sofia Martinez', '8', 'Daughter', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('49', 'Eric', 'F.', 'Ramirez', NULL, 'Eri', '1982-02-14', 'Male', 'Married', 'AB-', 'Filipino', '09179012345', 'eric.ramirez@example.com', 'Laura Ramirez', 'Wife', '09178901234', '7', 'Apple Avenue', 'Purok 3', 'Barangay Tres', 'Laura Ramirez', '9', 'Husband', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('50', 'Isabella', 'G.', 'Cruz', NULL, 'Bella', '1999-12-25', 'Female', 'Single', 'A+', 'Filipino', '09170123456', 'isabella.cruz@example.com', 'Miguel Cruz', 'Father', '09179012345', '88', 'Gumamela Street', 'Purok 1', 'Barangay Uno', 'Miguel Cruz', '10', 'Daughter', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('51', 'Ryan', 'H.', 'Lopez', NULL, 'Ry', '2001-04-12', 'Male', 'Single', 'O+', 'Filipino', '09171234500', 'ryan.lopez@example.com', 'Anna Lopez', 'Mother', '09170123400', '5', 'Lily Street', 'Purok 2', 'Barangay Dos', 'Anna Lopez', '11', 'Son', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('52', 'Clara', NULL, 'Santos', NULL, 'Clari', '1996-11-08', 'Female', 'Single', 'B+', 'Filipino', '09171234501', 'clara.santos@example.com', 'Jose Santos', 'Father', '09170123401', '42', 'Orchid Avenue', 'Purok 3', 'Barangay Tres', 'Jose Santos', '12', 'Daughter', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('53', 'Luis', 'I.', 'Reyes', NULL, 'Lu', '1989-07-19', 'Male', 'Married', 'AB+', 'Filipino', '09171234502', 'luis.reyes@example.com', 'Ana Reyes', 'Wife', '09170123402', '67', 'Mango Lane', 'Purok 1', 'Barangay Uno', 'Ana Reyes', '13', 'Husband', 'Resident', 'Active', '2025-08-28 16:20:36', '2025-08-28 16:20:36');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('54', 'Natalie', 'J.', 'Velasco', NULL, 'Nat', '1994-05-03', 'Female', 'Single', 'O+', 'Filipino', '09171234503', 'natalie.velasco@example.com', 'Carlos Velasco', 'Father', '09170123403', '15', 'Sunflower Street', 'Purok 2', 'Barangay Dos', 'Carlos Velasco', '14', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('55', 'Gabriel', NULL, 'De la Cruz', NULL, 'Gabe', '1987-09-14', 'Male', 'Married', 'A+', 'Filipino', '09171234504', 'gabriel.delacruz@example.com', 'Luz De la Cruz', 'Wife', '09170123404', '23', 'Acacia Avenue', 'Purok 3', 'Barangay Tres', 'Luz De la Cruz', '15', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('56', 'Vanessa', 'K.', 'Mendoza', NULL, 'Nessa', '1992-02-27', 'Female', 'Single', 'B+', 'Filipino', '09171234505', 'vanessa.mendoza@example.com', 'Ramon Mendoza', 'Father', '09170123405', '41', 'Rose Street', 'Purok 1', 'Barangay Uno', 'Ramon Mendoza', '16', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('57', 'Joshua', 'L.', 'Gonzalez', NULL, 'Josh', '1990-11-11', 'Male', 'Married', 'AB+', 'Filipino', '09171234506', 'joshua.gonzalez@example.com', 'Marta Gonzalez', 'Wife', '09170123406', '36', 'Tulip Avenue', 'Purok 2', 'Barangay Dos', 'Marta Gonzalez', '17', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('58', 'Angelica', NULL, 'Torres', NULL, 'Angie', '1995-07-08', 'Female', 'Single', 'O-', 'Filipino', '09171234507', 'angelica.torres@example.com', 'Jose Torres', 'Father', '09170123407', '12', 'Jasmine Street', 'Purok 3', 'Barangay Tres', 'Jose Torres', '18', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('59', 'Adrian', 'M.', 'Ramos', NULL, 'Adri', '1993-03-21', 'Male', 'Single', 'A-', 'Filipino', '09171234508', 'adrian.ramos@example.com', 'Liza Ramos', 'Mother', '09170123408', '18', 'Orchid Street', 'Purok 1', 'Barangay Uno', 'Liza Ramos', '19', 'Son', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('60', 'Bianca', NULL, 'Garcia', NULL, 'Bia', '1998-06-17', 'Female', 'Single', 'B-', 'Filipino', '09171234509', 'bianca.garcia@example.com', 'Roberto Garcia', 'Father', '09170123409', '33', 'Lily Avenue', 'Purok 2', 'Barangay Dos', 'Roberto Garcia', '20', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('61', 'Carlos', 'N.', 'Dela Fuente', NULL, 'Carl', '1985-10-09', 'Male', 'Married', 'AB-', 'Filipino', '09171234510', 'carlos.delafuente@example.com', 'Maria Dela Fuente', 'Wife', '09170123410', '50', 'Cedar Street', 'Purok 3', 'Barangay Tres', 'Maria Dela Fuente', '21', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('62', 'Elaine', NULL, 'Cabrera', NULL, 'Ela', '1991-12-19', 'Female', 'Single', 'O+', 'Filipino', '09171234511', 'elaine.cabrera@example.com', 'Julio Cabrera', 'Father', '09170123411', '27', 'Magnolia Street', 'Purok 1', 'Barangay Uno', 'Julio Cabrera', '22', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('63', 'Francis', 'O.', 'Santiago', NULL, 'Fran', '1989-04-02', 'Male', 'Married', 'A+', 'Filipino', '09171234512', 'francis.santiago@example.com', 'Luz Santiago', 'Wife', '09170123412', '11', 'Pineapple Avenue', 'Purok 2', 'Barangay Dos', 'Luz Santiago', '23', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('64', 'Gloria', 'P.', 'Medina', NULL, 'Glory', '1996-08-25', 'Female', 'Single', 'B+', 'Filipino', '09171234513', 'gloria.medina@example.com', 'Ramon Medina', 'Father', '09170123413', '60', 'Sunflower Lane', 'Purok 3', 'Barangay Tres', 'Ramon Medina', '24', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('65', 'Henry', NULL, 'Alcantara', NULL, 'Hank', '1988-01-30', 'Male', 'Married', 'AB+', 'Filipino', '09171234514', 'henry.alcantara@example.com', 'Isabel Alcantara', 'Wife', '09170123414', '9', 'Coconut Street', 'Purok 1', 'Barangay Uno', 'Isabel Alcantara', '25', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('66', 'Iris', 'Q.', 'Lopez', NULL, 'Iri', '1992-05-12', 'Female', 'Single', 'O-', 'Filipino', '09171234515', 'iris.lopez@example.com', 'Antonio Lopez', 'Father', '09170123415', '14', 'Cherry Lane', 'Purok 2', 'Barangay Dos', 'Antonio Lopez', '26', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('67', 'James', NULL, 'Gomez', NULL, 'Jim', '1987-07-04', 'Male', 'Married', 'A-', 'Filipino', '09171234516', 'james.gomez@example.com', 'Lucia Gomez', 'Wife', '09170123416', '30', 'Mango Street', 'Purok 3', 'Barangay Tres', 'Lucia Gomez', '27', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('68', 'Karen', 'R.', 'Villanueva', NULL, 'Kare', '1995-09-18', 'Female', 'Single', 'B-', 'Filipino', '09171234517', 'karen.villanueva@example.com', 'Ricardo Villanueva', 'Father', '09170123417', '19', 'Lily Street', 'Purok 1', 'Barangay Uno', 'Ricardo Villanueva', '28', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('69', 'Leo', NULL, 'Santos', NULL, 'Lee', '1990-03-05', 'Male', 'Single', 'AB-', 'Filipino', '09171234518', 'leo.santos@example.com', 'Maria Santos', 'Mother', '09170123418', '48', 'Orchid Avenue', 'Purok 2', 'Barangay Dos', 'Maria Santos', '29', 'Son', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('70', 'Maya', 'S.', 'Reyes', NULL, 'May', '1998-11-22', 'Female', 'Single', 'O+', 'Filipino', '09171234519', 'maya.reyes@example.com', 'Carlos Reyes', 'Father', '09170123419', '37', 'Tulip Street', 'Purok 3', 'Barangay Tres', 'Carlos Reyes', '30', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('71', 'Nathan', NULL, 'Cruz', NULL, 'Nate', '1985-06-15', 'Male', 'Married', 'A+', 'Filipino', '09171234520', 'nathan.cruz@example.com', 'Ana Cruz', 'Wife', '09170123420', '22', 'Banana Avenue', 'Purok 1', 'Barangay Uno', 'Ana Cruz', '31', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('72', 'Olivia', 'T.', 'Martinez', NULL, 'Liv', '1993-12-29', 'Female', 'Single', 'B+', 'Filipino', '09171234521', 'olivia.martinez@example.com', 'Roberto Martinez', 'Father', '09170123421', '6', 'Maple Street', 'Purok 2', 'Barangay Dos', 'Roberto Martinez', '32', 'Daughter', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('73', 'Patrick', NULL, 'Ramos', NULL, 'Pat', '1989-10-11', 'Male', 'Married', 'AB+', 'Filipino', '09171234522', 'patrick.ramos@example.com', 'Liza Ramos', 'Wife', '09170123422', '29', 'Acacia Lane', 'Purok 3', 'Barangay Tres', 'Liza Ramos', '33', 'Husband', 'Resident', 'Active', '2025-08-28 16:24:39', '2025-08-28 16:24:39');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('75', 'Angelo9', 'Landayan', 'ca', '', '', '2000-02-02', 'Male', '', '', '', '12312312312', 'admin@example.com', '', '', '', '9', '9', '9', 'Balagtas', '', NULL, '', 'Resident', 'Active', '2025-09-13 10:51:53', '2025-09-13 10:51:53');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('76', 'ethel', '', 'lastrollo', '', '', '2000-09-09', 'Female', '', '', '', '', '', '', '', '', '9', '9', '9', '9', '', NULL, '', 'Resident', 'Active', '2025-09-13 13:37:33', '2025-09-13 13:37:33');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('77', 'Angelo', 'Landayan', 'ca', '', '', '2025-09-01', 'Male', '', '', '', '12312312312', 'admin@example.com', '', '', '', '8', '8', '8', 'Balagtas', '', NULL, '', 'Resident', 'Active', '2025-09-25 06:35:17', '2025-09-25 12:35:17');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('78', 'Juan', '', 'Cruz', '', '', '2025-09-03', 'Male', '', '', '', '09179876543', 'juan@example.com', '', '', '', '12', 'Mango St', '1', 'Barangay 1', '', NULL, '', 'Resident', 'Active', '2025-09-25 06:59:34', '2025-09-25 12:59:34');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('79', 'Angelo', 'Landayan', 'ca', '', '', '2003-09-09', 'Male', '', '', '', '12312312312', 'admin@example.com', '', '', '', '5', '5', '5', 'Balagtas', '', NULL, '', 'Resident', 'Active', '2025-09-25 08:18:19', '2025-09-25 14:18:19');
INSERT INTO `residents` (`id`, `first_name`, `middle_name`, `last_name`, `suffix`, `nickname`, `dob`, `gender`, `civil_status`, `blood_type`, `nationality`, `contact_number`, `email`, `emergency_name`, `emergency_relation`, `emergency_number`, `house_no`, `street`, `purok`, `barangay`, `head_of_household`, `head_of_household_id`, `relationship`, `residency_status`, `status`, `date_added`, `last_updated`) VALUES ('80', 'Jeremy Benson', 'Garcia', 'Lastrollo', '', '', '2003-02-26', 'Male', '', '', '', '12312312312', 'admin@example.com', '', '', '', '3001', 'Palmera', '3', '3', '', NULL, '', 'Resident', 'Active', '2025-09-25 08:22:06', '2025-09-25 14:22:06');

DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `roles` (`id`, `role_name`) VALUES ('1', 'System Admin');
INSERT INTO `roles` (`id`, `role_name`) VALUES ('2', 'Barangay Admin');
INSERT INTO `roles` (`id`, `role_name`) VALUES ('3', 'Encoder');

DROP TABLE IF EXISTS `system_logs`;
CREATE TABLE `system_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `level` varchar(20) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `details` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('1', '2025-09-25 11:33:43', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('2', '2025-09-25 11:33:47', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('3', '2025-09-25 11:33:54', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('4', '2025-09-25 12:15:10', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('5', '2025-09-25 12:18:03', 'INFO', '2', 'Clerk', 'RESIDENT_UPDATE', 'Resident record ID#1 (Juan 3 woww pogi Cruz) was updated.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('6', '2025-09-25 12:18:19', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('7', '2025-09-25 12:20:13', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('8', '2025-09-25 12:20:47', 'INFO', '2', 'Clerk', 'SETTINGS_UPDATE', 'User \'Clerk\' changed their password.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('9', '2025-09-25 12:34:11', 'INFO', '2', 'Clerk', 'RESIDENT_DELETE', 'Resident record ID#1 was deleted.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('10', '2025-09-25 12:35:17', 'INFO', '2', 'Clerk', 'RESIDENT_CREATE', 'New resident record created: Angelo ca (ID#77).');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('11', '2025-09-25 12:35:27', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('12', '2025-09-25 12:35:35', 'WARNING', NULL, 'SYSTEM', 'USER_LOGIN_FAIL', 'Failed login attempt for username: \'admin\'');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('13', '2025-09-25 12:35:41', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('14', '2025-09-25 12:37:47', 'INFO', '4', 'sysadmin', 'USER_UPDATE', 'User account \'Clerk\' (ID#2) was updated.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('15', '2025-09-25 12:38:47', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('16', '2025-09-25 12:40:52', 'INFO', '2', 'Clerk', 'RESIDENT_UPDATE', 'Resident record ID#11 (Juan woww pogi 34 Cruz) was updated.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('17', '2025-09-25 12:41:03', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('18', '2025-09-25 12:41:10', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('19', '2025-09-25 12:50:08', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('20', '2025-09-25 12:50:19', 'INFO', '2', 'Clerk', 'RESIDENT_UPDATE', 'Updated resident ID#2. Changes: first_name changed from \'Maria Wowers Galing\' to \'Maria Wowers Galing WOWOW\', last_updated changed from \'2025-08-28 04:15:52\' to \'2025-09-25 06:50:19\'.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('21', '2025-09-25 12:50:25', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('22', '2025-09-25 12:50:34', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('23', '2025-09-25 12:51:48', 'INFO', '4', 'sysadmin', 'USER_CREATE', 'New user \'encoder2\' (ID#6) was created.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('24', '2025-09-25 12:56:44', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('25', '2025-09-25 12:57:31', 'INFO', '2', 'Clerk', 'RESIDENT_DELETE', 'Resident record ID#2 was deleted.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('26', '2025-09-25 12:57:41', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('27', '2025-09-25 12:57:51', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('28', '2025-09-25 12:59:11', 'INFO', '6', 'encoder2', 'USER_LOGIN_SUCCESS', 'User \'encoder2\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('29', '2025-09-25 12:59:34', 'INFO', '6', 'encoder2', 'RESIDENT_CREATE', 'New resident record created: Juan Cruz (ID#78).');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('30', '2025-09-25 12:59:48', 'INFO', '6', 'encoder2', 'USER_LOGOUT', 'User \'encoder2\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('31', '2025-09-25 12:59:58', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('32', '2025-09-25 13:51:57', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('33', '2025-09-25 14:17:33', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('34', '2025-09-25 14:18:19', 'INFO', '2', 'Clerk', 'RESIDENT_CREATE', 'New resident record created: Angelo ca (ID#79).');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('35', '2025-09-25 14:19:17', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('36', '2025-09-25 14:19:25', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('37', '2025-09-25 14:20:14', 'INFO', '2', 'Clerk', 'USER_LOGIN_SUCCESS', 'User \'Clerk\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('38', '2025-09-25 14:20:48', 'INFO', '2', 'Clerk', 'USER_LOGOUT', 'User \'Clerk\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('39', '2025-09-25 14:21:02', 'WARNING', NULL, 'SYSTEM', 'USER_LOGIN_FAIL', 'Failed login attempt for username: \'encoder1\'');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('40', '2025-09-25 14:21:04', 'WARNING', NULL, 'SYSTEM', 'USER_LOGIN_FAIL', 'Failed login attempt for username: \'encoder1\'');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('41', '2025-09-25 14:21:06', 'WARNING', NULL, 'SYSTEM', 'USER_LOGIN_FAIL', 'Failed login attempt for username: \'encoder1\'');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('42', '2025-09-25 14:21:09', 'WARNING', NULL, 'SYSTEM', 'USER_LOGIN_FAIL', 'Failed login attempt for username: \'encoder1\'');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('43', '2025-09-25 14:21:12', 'INFO', '5', 'encoder1', 'USER_LOGIN_SUCCESS', 'User \'encoder1\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('44', '2025-09-25 14:22:06', 'INFO', '5', 'encoder1', 'RESIDENT_CREATE', 'New resident record created: Jeremy Benson Lastrollo (ID#80).');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('45', '2025-09-25 14:22:27', 'INFO', '5', 'encoder1', 'USER_LOGOUT', 'User \'encoder1\' logged out.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('46', '2025-09-25 14:22:41', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('47', '2025-09-25 14:43:44', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('48', '2025-09-25 15:48:07', 'INFO', '4', 'sysadmin', 'USER_LOGIN_SUCCESS', 'User \'sysadmin\' logged in successfully.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('49', '2025-09-25 16:03:23', 'ERROR', '4', 'sysadmin', 'DB_BACKUP_FAIL', 'Database backup failed.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('50', '2025-09-25 16:07:01', 'ERROR', '4', 'sysadmin', 'DB_BACKUP_FAIL', 'Database backup failed.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('51', '2025-09-25 16:07:03', 'ERROR', '4', 'sysadmin', 'DB_BACKUP_FAIL', 'Database backup failed.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('52', '2025-09-25 16:07:04', 'ERROR', '4', 'sysadmin', 'DB_BACKUP_FAIL', 'Database backup failed.');
INSERT INTO `system_logs` (`id`, `timestamp`, `level`, `user_id`, `username`, `action`, `details`) VALUES ('53', '2025-09-25 16:08:16', 'ERROR', '4', 'sysadmin', 'DB_BACKUP_FAIL', 'Database backup failed: ');

DROP TABLE IF EXISTS `user_analytics_layouts`;
CREATE TABLE `user_analytics_layouts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `layout` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`layout`)),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `user_analytics_layouts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `user_analytics_layouts` (`id`, `user_id`, `layout`, `updated_at`) VALUES ('15', '2', '[{\"id\":\"average_age_of_residents\",\"x\":0,\"y\":0,\"w\":3,\"h\":2},{\"id\":\"average_household_size\",\"x\":3,\"y\":0,\"w\":3,\"h\":2},{\"id\":\"sex_ratio\",\"x\":9,\"y\":0,\"w\":3,\"h\":2},{\"id\":\"population_pyramid\",\"x\":0,\"y\":2,\"w\":6,\"h\":6},{\"id\":\"dependency_ratio\",\"x\":6,\"y\":3,\"w\":3,\"h\":2},{\"id\":\"generation_breakdown\",\"x\":6,\"y\":5,\"w\":6,\"h\":6},{\"id\":\"detailed_age_brackets\",\"x\":0,\"y\":8,\"w\":6,\"h\":4},{\"id\":\"civil_status_distribution_by_gender\",\"x\":6,\"y\":11,\"w\":6,\"h\":4},{\"id\":\"household_size_distribution\",\"x\":0,\"y\":12,\"w\":4,\"h\":4},{\"id\":\"heads_of_household_by_gender\",\"x\":4,\"y\":15,\"w\":4,\"h\":4},{\"id\":\"relationship\",\"x\":8,\"y\":15,\"w\":4,\"h\":4},{\"id\":\"purok\",\"x\":0,\"y\":19,\"w\":6,\"h\":4},{\"id\":\"voter_population_by_purok\",\"x\":6,\"y\":19,\"w\":6,\"h\":4},{\"id\":\"senior_citizens_by_purok\",\"x\":0,\"y\":23,\"w\":6,\"h\":4},{\"id\":\"school_age_population_by_purok\",\"x\":6,\"y\":23,\"w\":6,\"h\":4},{\"id\":\"residents_per_street\",\"x\":0,\"y\":27,\"w\":6,\"h\":4},{\"id\":\"nationality\",\"x\":6,\"y\":27,\"w\":3,\"h\":4},{\"id\":\"blood_type\",\"x\":9,\"y\":27,\"w\":3,\"h\":4},{\"id\":\"profile_completeness\",\"x\":0,\"y\":31,\"w\":4,\"h\":4},{\"id\":\"emergency_contact_coverage\",\"x\":4,\"y\":31,\"w\":4,\"h\":4},{\"id\":\"resident_status_overview\",\"x\":8,\"y\":31,\"w\":4,\"h\":4}]', '2025-09-25 12:38:59');

DROP TABLE IF EXISTS `user_chart_settings`;
CREATE TABLE `user_chart_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `chart_id` varchar(255) NOT NULL,
  `size` int(11) NOT NULL DEFAULT 1,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_chart` (`user_id`,`chart_id`),
  CONSTRAINT `user_chart_settings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `user_dashboards`;
CREATE TABLE `user_dashboards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `dashboard_config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`dashboard_config`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `user_dashboards_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `user_dashboards` (`id`, `user_id`, `dashboard_config`, `created_at`, `updated_at`) VALUES ('1', '2', '[]', '2025-09-02 10:19:57', '2025-09-02 10:20:23');

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role_id` int(11) NOT NULL,
  `barangay_id` int(11) DEFAULT NULL,
  `full_name` varchar(100) NOT NULL,
  `theme` enum('light','dark') NOT NULL DEFAULT 'light',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`id`, `username`, `password`, `role_id`, `barangay_id`, `full_name`, `theme`) VALUES ('2', 'Clerk', '$2y$10$BRjPJ8Z51vTlIWkIH/5GgOZeRZLD0zSBikfSvC7H4.wIwuxF89Zgi', '2', '1', 'Barangay Administrator', 'dark');
INSERT INTO `users` (`id`, `username`, `password`, `role_id`, `barangay_id`, `full_name`, `theme`) VALUES ('3', 'encoder', '$2y$10$Y9veDWYoP/P5jd/mMgUxQuZ4hjtKxk8aiwiOeROkFsJnqB6oeEBCO', '3', '1', 'Test Encoder', 'light');
INSERT INTO `users` (`id`, `username`, `password`, `role_id`, `barangay_id`, `full_name`, `theme`) VALUES ('4', 'sysadmin', '$2y$10$sEUidf2rUPWhU3AUxswQme0GnwG9OGiJFEhs9/X.zTJe9RtH8p8GG', '1', NULL, 'System Administrator', 'light');
INSERT INTO `users` (`id`, `username`, `password`, `role_id`, `barangay_id`, `full_name`, `theme`) VALUES ('5', 'encoder1', '$2y$10$GojEylRJE8KvfnYddpy8QeCrIRA4RaisHG21xjO5CHILO7rABRFO.', '3', NULL, 'Encoder', 'light');
INSERT INTO `users` (`id`, `username`, `password`, `role_id`, `barangay_id`, `full_name`, `theme`) VALUES ('6', 'encoder2', '$2y$10$9HZWDAi5rl.r1yE3TyAMteTeEuPM0gJ9WygAcU4Y1QR6QgBx/PcB2', '3', '1', 'Encoder', 'light');

