<?php
session_start();

// --- Bouncer ---
if (!isset($_SESSION['user']) || $_SESSION['user']['role_name'] != 'Barangay Admin') {
    http_response_code(403);
    die("<h1>403 Forbidden</h1><p>You do not have permission to access this page.</p>");
}

// --- Includes ---
$config = require __DIR__ . '/config.php';
require __DIR__ . '/Database.php';

$db = new Database($config);
$pdo = $db->getPdo();

// --- Get Post Data ---
$purok = $_POST['filter_purok'] ?? '';
$gender = $_POST['filter_gender'] ?? '';
$civil_status = $_POST['filter_civil_status'] ?? '';
$status = $_POST['filter_status'] ?? '';
$age_min = $_POST['age_min'] ?? '';
$age_max = $_POST['age_max'] ?? '';
$sort_by = $_POST['sort_by'] ?? 'last_name';
$sort_order = $_POST['sort_order'] ?? 'ASC';
$selected_columns = $_POST['columns'] ?? [];
$font_size = $_POST['font_size'] ?? '12px';

// --- Security, Validation, and Column Mapping ---
$allowed_sort_columns = ['last_name', 'first_name', 'date_added', 'dob'];
if (!in_array($sort_by, $allowed_sort_columns)) {
    $sort_by = 'last_name';
}
$sort_order = ($sort_order === 'DESC') ? 'DESC' : 'ASC';

$all_columns = [
    'full_name' => ['label' => 'Full Name', 'sql' => "CONCAT(first_name, ' ', last_name)"],
    'address' => ['label' => 'Full Address', 'sql' => "CONCAT(house_no, ' ', street, ', Purok ', purok, ', ', barangay)"],
    'dob' => ['label' => 'Date of Birth', 'sql' => 'dob'],
    'age' => ['label' => 'Age', 'sql' => 'TIMESTAMPDIFF(YEAR, dob, CURDATE())'],
    'gender' => ['label' => 'Gender', 'sql' => 'gender'],
    'civil_status' => ['label' => 'Civil Status', 'sql' => 'civil_status'],
    'contact_number' => ['label' => 'Contact Number', 'sql' => 'contact_number'],
    'email' => ['label' => 'Email', 'sql' => 'email'],
    'blood_type' => ['label' => 'Blood Type', 'sql' => 'blood_type'],
    'nationality' => ['label' => 'Nationality', 'sql' => 'nationality'],
    'status' => ['label' => 'Resident Status', 'sql' => 'status'],
    'date_added' => ['label' => 'Date Added', 'sql' => 'date_added']
];

$columns_to_select = [];
$report_headers = [];
if (!empty($selected_columns)) {
    foreach ($selected_columns as $col) {
        if (array_key_exists($col, $all_columns)) {
            $columns_to_select[$col] = $all_columns[$col]['sql'] . " AS " . $col;
            $report_headers[$col] = $all_columns[$col]['label'];
        }
    }
}

if(empty($columns_to_select)){ // Default columns if none are selected
    $default_cols = ['full_name', 'address', 'age', 'gender', 'status'];
    foreach($default_cols as $col){
        $columns_to_select[$col] = $all_columns[$col]['sql'] . " AS " . $col;
        $report_headers[$col] = $all_columns[$col]['label'];
    }
}

// --- Build Query ---
$sql = "SELECT " . implode(", ", $columns_to_select) . " FROM residents";
$conditions = [];
$params = [];

if (!empty($purok)) { $conditions[] = "purok = ?"; $params[] = $purok; }
if (!empty($gender)) { $conditions[] = "gender = ?"; $params[] = $gender; }
if (!empty($civil_status)) { $conditions[] = "civil_status = ?"; $params[] = $civil_status; }
if (!empty($status)) { $conditions[] = "status = ?"; $params[] = $status; }
if (is_numeric($age_min) && $age_min >= 0) { $conditions[] = "TIMESTAMPDIFF(YEAR, dob, CURDATE()) >= ?"; $params[] = $age_min; }
if (is_numeric($age_max) && $age_max >= 0) { $conditions[] = "TIMESTAMPDIFF(YEAR, dob, CURDATE()) <= ?"; $params[] = $age_max; }

if (!empty($conditions)) {
    $sql .= " WHERE " . implode(" AND ", $conditions);
}
$sql .= " ORDER BY $sort_by $sort_order";

$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$results = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Custom Resident Report</title>
    <style>
        body { font-family: sans-serif; font-size: <?= htmlspecialchars($font_size) ?>; }
        .header { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; word-break: break-word; }
        th { background-color: #f2f2f2; }
        .no-print { position: fixed; top: 10px; right: 10px; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>
    <div class="no-print">
        <button onclick="window.print()">Print Report</button>
    </div>
    <div class="header">
        <h1>Resident Report</h1>
        <p>Generated By: <strong><?= htmlspecialchars($_SESSION['user']['full_name']) ?></strong> on <?= date('Y-m-d H:i:s') ?></p>
    </div>
    <table>
        <thead>
            <tr>
                <?php foreach ($report_headers as $header): ?>
                    <th><?= htmlspecialchars($header) ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($results)): ?>
                <tr>
                    <td colspan="<?= count($report_headers) ?>" style="text-align: center;">No residents found with the selected criteria.</td>
                </tr>
            <?php else: ?>
                <?php foreach ($results as $row): ?>
                    <tr>
                        <?php foreach (array_keys($report_headers) as $col_key): ?>
                            <td><?= htmlspecialchars($row[$col_key] ?? '') ?></td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</body>
</html>